name: Terraform
on:
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-stage
      uses: actions/checkout@v4.1.2
    - name: terraform setup
      uses: hashicorp/setup-terraform@v2.0.3
    - name: aws login
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ap-south-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: terraform fmt
      run: terraform fmt
