name: Terraform
on:
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-stage
      uses: actions/checkout@v4.1.2
    - name: terraform setup
      uses: hashicorp/setup-terraform@v2.0.3
    - name: terraform fmt
      run: terraform fmt
